# Generated by Django 4.2 on 2023-04-18 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applicationRequests", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="loan",
            name="paid_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
