# Generated by Django 4.2 on 2023-04-19 13:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applicationRequests", "0003_remove_loan_paid_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="loan",
            name="date",
            field=models.DateField(default=datetime.date(2022, 4, 20)),
        ),
        migrations.AddField(
            model_name="loan",
            name="payment_per_month",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="payment per month",
                max_digits=10,
            ),
        ),
    ]
