# Generated by Django 4.2 on 2023-04-19 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "applicationRequests",
            "0005_payment_installment_date_alter_payment_payment_date",
        ),
    ]

    operations = [
        migrations.RemoveField(model_name="payment", name="installment_date",),
    ]
